AllCops:
  Exclude:
  - bundle/**/*
  TargetRubyVersion: 2.3

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 230

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 52

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 10

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/FrozenStringLiteralComment:
  Enabled: false
